export enum PlaceholderCode {
  Null = 0x00,
  TextStart = 0x01,
  TextEnd = 0x02,
  Code03,
  Code04,
  Code05,
  Code06,
  Code07,
  Code08,
  Code09,
  Code0a,
  Code0b,
  Code0c,
  ParagraphReturn = 0x0d,
  Code0e,
  Code0f,
  Code10,
  Code11,
  Code12,
  Code13,
  Code14,
  Code15,
  Code16,
  Code17,
  Code18,
  Code19,
  Code1a,
  Code1b,
  Code1c,
  Code1d,
  Code1e,
  Code1f,
}

export const PlaceholderChar = {
  Null: String.fromCharCode(PlaceholderCode.Null),
  TextStart: String.fromCharCode(PlaceholderCode.TextStart),
  TextEnd: String.fromCharCode(PlaceholderCode.TextEnd),
  ParagraphReturn: String.fromCharCode(PlaceholderCode.ParagraphReturn),
};
